// Copyright (c) 2026 NineMind, Inc.
// SPDX-License-Identifier: MIT
// src/gemit/cohort.ts
//
// Where an operator stands against everyone else who shared a card. The report is
// provably offline (gemitTheme.test.ts forbids any URL in the output), so the
// distribution ships BAKED into the package rather than fetched — regenerated by
// scripts/gemit-cohort.mjs from real published cards.
//
// COHORT is null until that script has actually been run. A table of plausible-looking
// numbers would be fabricated social proof in a document whose footer advertises
// deterministic scoring, so absence is the correct default, not a placeholder.

export interface Cohort {
  /** ISO date the table was generated. Rendered, so staleness is disclosed. */
  asOf: string;
  /** Sample size the percentiles were computed from. */
  n: number;
  /** index = composite 0..100, value = percentile 0..99. */
  p: number[];
}

/** Below this many cards a percentile is noise dressed as a fact. */
export const MIN_COHORT = 100;

export const COHORT: Cohort | null = null;

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export function percentileFor(composite: number, c?: Cohort | null): number | null {
  if (!c || c.n < MIN_COHORT || c.p.length !== 101) return null;
  const i = Math.max(0, Math.min(100, Math.round(composite)));
  const v = c.p[i];
  return typeof v === "number" ? v : null;
}

// "Top N%" for a composite is the inverse of the percentile: the share of the
// cohort AT OR BELOW the composite is how good it is, so the share ABOVE it (the
// "top" fraction) is 100 minus that. Single-sourced here so the card
// (themeRpg.ts) and the share text (share.ts) can never compute this differently
// from one another — both call this, neither re-derives `100 - pct` on its own.
//
// HAZARD, tracked but deliberately NOT fixed here: this fraction is unbounded. Once
// a real cohort table lands (COHORT stops being null), a middling composite can
// render "top 88%" in a report published under the operator's own name —
// mathematically correct, reads as sarcasm about the person who just shared it.
// Whoever lands the real table MUST add a clamp (floor the displayed fraction, or
// suppress the claim below some percentile — copy decision, not just a number)
// applied to this function so BOTH callers pick it up together. Never patch
// themeRpg.ts's card or share.ts's standingClause alone; a clamp on only one side
// reopens exactly the drift this single-sourcing was built to prevent.
export function topPercentFor(composite: number, c?: Cohort | null): number | null {
  const pct = percentileFor(composite, c);
  return pct === null ? null : 100 - pct;
}

export function cohortLabel(c: Cohort): string {
  const [y, m] = c.asOf.split("-");
  const month = MONTHS[Number(m) - 1] ?? m;
  return `of ${c.n.toLocaleString("en-US")} shared cards, ${month} ${y}`;
}
