// Copyright (c) 2026 NineMind, Inc.
// SPDX-License-Identifier: MIT
// src/gem/mcpProxy.ts
// Shared, target-agnostic generator for a stdio->Streamable-HTTP MCP proxy runner. A url-only
// target (Eve today) can't connect to a stdio (command) MCP server directly; instead we emit a
// self-contained runner the operator launches where the agent runs. It spawns the stdio server and
// re-serves it over HTTP, so the agent connects to http://localhost:<port>/mcp.
//
// agentgem only RENDERS the script (pure text — no @modelcontextprotocol/sdk dependency here); the
// operator installs the SDK where they run it. Secrets are never embedded: the proxy passes the
// operator's environment through to the spawned server, and the file lists the env-var names needed.

export const PROXY_BASE_PORT = 7800;
export const PROXY_HOST = "127.0.0.1";

const commentText = (value: string): string => value.replace(/[\r\n\u2028\u2029]/g, " ");

export function stdioProxyRunner(name: string, command: string, args: string[], secretEnvs: string[], port: number): string {
  const safeName = commentText(name);
  const secretNote = secretEnvs.length
    ? `// Set these env vars before running (the underlying server reads them): ${commentText(secretEnvs.join(", "))}\n`
    : "";
  return `#!/usr/bin/env node
// Auto-generated by agentgem — stdio->HTTP MCP proxy for ${JSON.stringify(name)}.
// Run it alongside your agent:  node agent/proxies/${safeName}.mjs
// Install where you run it:     npm i @modelcontextprotocol/sdk express
${secretNote}import express from "express";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import {
  ListToolsRequestSchema, CallToolRequestSchema,
  ListPromptsRequestSchema, GetPromptRequestSchema,
  ListResourcesRequestSchema, ReadResourceRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

// Connect to the real stdio MCP server (inherits this process's env for any secrets it needs).
const upstream = new Client({ name: "agentgem-proxy", version: "1.0.0" }, { capabilities: {} });
await upstream.connect(new StdioClientTransport({ command: ${JSON.stringify(command)}, args: ${JSON.stringify(args)}, env: process.env }));

// Re-serve it over Streamable HTTP, forwarding the standard MCP methods to the upstream client.
const server = new Server({ name: ${JSON.stringify(name)}, version: "1.0.0" }, { capabilities: { tools: {}, prompts: {}, resources: {} } });
server.setRequestHandler(ListToolsRequestSchema, () => upstream.listTools());
server.setRequestHandler(CallToolRequestSchema, (r) => upstream.callTool(r.params));
server.setRequestHandler(ListPromptsRequestSchema, () => upstream.listPrompts());
server.setRequestHandler(GetPromptRequestSchema, (r) => upstream.getPrompt(r.params));
server.setRequestHandler(ListResourcesRequestSchema, () => upstream.listResources());
server.setRequestHandler(ReadResourceRequestSchema, (r) => upstream.readResource(r.params));

const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
await server.connect(transport);
const app = express();
app.use(express.json());
app.all("/mcp", (req, res) => transport.handleRequest(req, res, req.body));
app.listen(${port}, ${JSON.stringify(PROXY_HOST)}, () => console.error(${JSON.stringify(`[agentgem proxy] ${name} -> http://${PROXY_HOST}:${port}/mcp`)}));
`;
}
